--liquibase formatted sql

--changeset timurnav:1
CREATE SEQUENCE IF NOT EXISTS GLOBAL_SEQ START WITH 100000;

CREATE TABLE IF NOT EXISTS USERS
(
    ID         INTEGER PRIMARY KEY DEFAULT NEXTVAL('GLOBAL_SEQ'),
    USER_TYPE  VARCHAR   NOT NULL,
    FIRST_NAME VARCHAR   NOT NULL,
    LAST_NAME  VARCHAR   NOT NULL,
    REGISTERED TIMESTAMP NOT NULL  DEFAULT NOW(),
    MANAGER_ID INTEGER,
    FOREIGN KEY (MANAGER_ID) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS CONTACTS
(
    ID            INTEGER PRIMARY KEY DEFAULT NEXTVAL('GLOBAL_SEQ'),
    EMAIL         VARCHAR UNIQUE,
    PHONE_NUMBER  VARCHAR UNIQUE,
    TELEGRAM_LINK VARCHAR UNIQUE,
    LINKEDIN_LINK VARCHAR UNIQUE,
    GITHUB_LINK   VARCHAR UNIQUE,
    FACEBOOK_LINK VARCHAR UNIQUE,
    USER_ID       INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COURSES
(
    ID          INTEGER PRIMARY KEY DEFAULT NEXTVAL('GLOBAL_SEQ'),
    TITLE       VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    TEACHER_ID  INTEGER,
    FOREIGN KEY (TEACHER_ID) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS STUDENT_COURSE
(
    STUDENT_ID INTEGER,
    COURSE_ID  INTEGER,
    CONSTRAINT STUDENT_COURSES_IDX UNIQUE (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS LESSONS
(
    ID          INTEGER PRIMARY KEY DEFAULT NEXTVAL('GLOBAL_SEQ'),
    TITLE       VARCHAR   NOT NULL,
    DESCRIPTION VARCHAR   NOT NULL,
    DATE        TIMESTAMP NOT NULL,
    COURSE_ID   INTEGER,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HOME_WORKS
(
    ID          INTEGER PRIMARY KEY DEFAULT NEXTVAL('GLOBAL_SEQ'),
    TITLE       VARCHAR   NOT NULL,
    DESCRIPTION VARCHAR   NOT NULL,
    TILL        TIMESTAMP NOT NULL,
    ATTEMPTS    INTEGER   NOT NULL,
    LESSON_ID   INTEGER,
    FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID) ON DELETE CASCADE
);
